[build]
  functions = "netlify/functions"
  publish = "/"

# Ensure functions aren't swallowed by SPA redirect
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
